#docker-compose.test.yml (Extended config for TEST env.)
version: '3.5'

services:
  faster.web:
    depends_on:
      - faster-pgsql
    image: 'faster.web'
    build:
      context: .
      dockerfile: src/Ermes.Web/Dockerfile
    restart: unless-stopped  
    environment:
      - ASPNETCORE_ENVIRONMENT=FasterTest
      - GOOGLE_APPLICATION_CREDENTIALS=firebasekey-faster.json
    ports:
      - '${FASTER_WEB_PORT_TEST}:80'
    container_name: 'faster-web-${ENVTYPE_TEST}'
    networks:
      - faster-net
    volumes:
      - fasterlogstest:/app/App_Data/Logs/
    env_file:
      - ./.env

  faster-pgsql:
    image: 'faster-pgsql'
    build:
      context: .
      dockerfile: src/containers/postgresql/Dockerfile
    restart: unless-stopped  
    container_name: 'faster-pgsql-${ENVTYPE_TEST}'
    networks:
      - faster-net
    environment:
      POSTGRES_PASSWORD: ${FASTER_PASSWORD_TEST}
      DB_PASSWORD: ${FASTER_PASSWORD_TEST}
      DB_NAME: ${FASTER_DB_TEST}
      DB_USER: ${FASTER_USER_TEST}
    ports:
      - '${PGSQL_PORT_TEST}:5432'

networks:
  faster-net:
    name: faster-net-${ENVTYPE_TEST}

volumes:
  fasterlogstest: