#docker-compose.shelter-local.yml (Extended config for Local env.)
version: '3.5'

services:
  shelter.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      - GOOGLE_APPLICATION_CREDENTIALS=firebasekey-dev.json
    ports:
      - '${SHELTER_WEB_PORT_LOCAL}:80'
    container_name: 'shelter-web-${ENVTYPE_LOCAL}'
    env_file: 
      - ./.env
    depends_on:
      - shelter-pgsql
    image: 'shelter.web'
    build:
      context: .
      dockerfile: src/Ermes.Web/Dockerfile
    restart: unless-stopped      

  shelter-pgsql:
    container_name: 'shelter-pgsql-${ENVTYPE_LOCAL}'
    environment:
      POSTGRES_PASSWORD: ${SHELTER_PASSWORD_LOCAL}
      DB_PASSWORD: ${SHELTER_PASSWORD_LOCAL}
      DB_NAME: ${SHELTER_DB_LOCAL}
      DB_USER: ${SHELTER_USER_LOCAL}
    ports:
      - '${PGSQL_PORT_SHELTER_LOCAL}:5432'
    image: 'shelter-pgsql'
    build:
      context: .
      dockerfile: src/containers/postgresql/Dockerfile
    restart: unless-stopped      
