#docker-compose.safers.test.yml (Extended config for Safers TEST env.)
version: '3.5'

services:
  safers.web:
    depends_on:
      - safers-pgsql
    image: 'safers.web'
    build:
      context: .
      dockerfile: src/Ermes.Web/Dockerfile
    restart: unless-stopped  
    environment:
      - ASPNETCORE_ENVIRONMENT=SafersTest
      - GOOGLE_APPLICATION_CREDENTIALS=firebasekey-safers.json
    ports:
      - '${SAFERS_WEB_PORT_TEST}:80'
    container_name: 'safers-web-${ENVTYPE_SAFERS_TEST}'
    networks:
      - safers-net
    volumes:
      - saferslogstest:/app/App_Data/Logs/      
    env_file:
      - ./.env    

  safers-pgsql:
    image: 'safers-pgsql'
    build:
      context: .
      dockerfile: src/containers/postgresql/Dockerfile
    restart: unless-stopped  
    container_name: 'safers-pgsql-${ENVTYPE_SAFERS_TEST}'
    networks:
      - safers-net    
    volumes:
      - safersdbdatatest:/var/lib/postgresql/data         
    environment:
      POSTGRES_PASSWORD: ${SAFERS_PASSWORD_TEST}
      DB_PASSWORD: ${SAFERS_PASSWORD_TEST}
      DB_NAME: ${SAFERS_DB_TEST}
      DB_USER: ${SAFERS_USER_TEST}
    ports:
      - '${PGSQL_PORT_SAFERS_TEST}:5432'

networks:
  safers-net:
    name: safers-net-${ENVTYPE_SAFERS_TEST}

volumes:
  saferslogstest:
  safersdbdatatest:

