#docker-compose.development.yml (Extended config for DEVELOPMENT env.)
version: '3.5'

services:
  faster.web:
    depends_on:
      - faster-pgsql
    image: 'faster.web'
    build:
      context: .
      dockerfile: src/Ermes.Web/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=FasterDevelopment
      - GOOGLE_APPLICATION_CREDENTIALS=firebasekey-faster.json
    ports:
      - '${FASTER_WEB_PORT_DEV}:80'
    container_name: 'faster-web-${ENVTYPE_DEV}'
    networks:
      - faster-net
    volumes:
      - fasterlogsdev:/app/App_Data/Logs/
    env_file:
      - ./.env    

  faster-pgsql:
    image: 'faster-pgsql'
    build:
      context: .
      dockerfile: src/containers/postgresql/Dockerfile
    restart: unless-stopped
    container_name: 'faster-pgsql-${ENVTYPE_DEV}'
    networks:
      - faster-net    
    environment:
      POSTGRES_PASSWORD: ${FASTER_PASSWORD_DEV}
      DB_PASSWORD: ${FASTER_PASSWORD_DEV}
      DB_NAME: ${FASTER_DB_DEV}
      DB_USER: ${FASTER_USER_DEV}
    ports:
      - '${PGSQL_PORT_DEV}:5432'

networks:
  faster-net:
    name: faster-net-${ENVTYPE_DEV}

volumes:
  fasterlogsdev:

