#docker-compose.shelter.development.yml (Extended config for Shelter DEVELOPMENT env.)
version: '3.5'

services:
  shelter.web:
    depends_on:
      - shelter-pgsql
    image: 'shelter.web'
    build:
      context: .
      dockerfile: src/Ermes.Web/Dockerfile
    restart: unless-stopped  
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - GOOGLE_APPLICATION_CREDENTIALS=firebasekey-shelter.json
    ports:
      - '${SHELTER_WEB_PORT_DEV}:80'
    container_name: 'shelter-web-${ENVTYPE_DEV}'
    networks:
      - shelter-net
    volumes:
      - shelterlogsdev:/app/App_Data/Logs/      
    env_file:
      - ./.env    

  shelter-pgsql:
    image: 'shelter-pgsql'
    build:
      context: .
      dockerfile: src/containers/postgresql/Dockerfile
    restart: unless-stopped  
    container_name: 'shelter-pgsql-${ENVTYPE_DEV}'
    networks:
      - shelter-net    
    environment:
      POSTGRES_PASSWORD: ${SHELTER_PASSWORD_DEV}
      DB_PASSWORD: ${SHELTER_PASSWORD_DEV}
      DB_NAME: ${SHELTER_DB_DEV}
      DB_USER: ${SHELTER_USER_DEV}
    ports:
      - '${PGSQL_PORT_SHELTER_DEV}:5432'

networks:
  shelter-net:
    name: shelter-net-${ENVTYPE_SHELTER_DEV}

volumes:
  shelterlogsdev:

