/*
 * Event Detection Module - Public API
 *
 *  ### Public endpoints for the Social Media Analysis module (SMA). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Abp.ErmesSocialNetCore.Client;
using Abp.ErmesSocialNetCore.Model;

namespace Abp.ErmesSocialNetCore.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a paged list of media entities
        /// </summary>
        /// <remarks>
        /// Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <returns>Pagination</returns>
        Pagination ApiV1MediaGet(int? page = default(int?), int? limit = default(int?));

        /// <summary>
        /// Gets a paged list of media entities
        /// </summary>
        /// <remarks>
        /// Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <returns>ApiResponse of Pagination</returns>
        ApiResponse<Pagination> ApiV1MediaGetWithHttpInfo(int? page = default(int?), int? limit = default(int?));
        /// <summary>
        /// Gets a single media entity
        /// </summary>
        /// <remarks>
        /// Retrieves a single media entity from the ID provided in the path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <returns>Media</returns>
        Media ApiV1MediaMediaIdGet(long mediaId);

        /// <summary>
        /// Gets a single media entity
        /// </summary>
        /// <remarks>
        /// Retrieves a single media entity from the ID provided in the path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <returns>ApiResponse of Media</returns>
        ApiResponse<Media> ApiV1MediaMediaIdGetWithHttpInfo(long mediaId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets a paged list of media entities
        /// </summary>
        /// <remarks>
        /// Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Pagination</returns>
        System.Threading.Tasks.Task<Pagination> ApiV1MediaGetAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a paged list of media entities
        /// </summary>
        /// <remarks>
        /// Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Pagination)</returns>
        System.Threading.Tasks.Task<ApiResponse<Pagination>> ApiV1MediaGetWithHttpInfoAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets a single media entity
        /// </summary>
        /// <remarks>
        /// Retrieves a single media entity from the ID provided in the path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Media</returns>
        System.Threading.Tasks.Task<Media> ApiV1MediaMediaIdGetAsync(long mediaId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a single media entity
        /// </summary>
        /// <remarks>
        /// Retrieves a single media entity from the ID provided in the path.
        /// </remarks>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Media)</returns>
        System.Threading.Tasks.Task<ApiResponse<Media>> ApiV1MediaMediaIdGetWithHttpInfoAsync(long mediaId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApi : IMediaApiSync, IMediaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MediaApi : IMediaApi
    {
        private Abp.ErmesSocialNetCore.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MediaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MediaApi(String basePath)
        {
            this.Configuration = Abp.ErmesSocialNetCore.Client.Configuration.MergeConfigurations(
                Abp.ErmesSocialNetCore.Client.GlobalConfiguration.Instance,
                new Abp.ErmesSocialNetCore.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Abp.ErmesSocialNetCore.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Abp.ErmesSocialNetCore.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Abp.ErmesSocialNetCore.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MediaApi(Abp.ErmesSocialNetCore.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Abp.ErmesSocialNetCore.Client.Configuration.MergeConfigurations(
                Abp.ErmesSocialNetCore.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Abp.ErmesSocialNetCore.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Abp.ErmesSocialNetCore.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Abp.ErmesSocialNetCore.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MediaApi(Abp.ErmesSocialNetCore.Client.ISynchronousClient client, Abp.ErmesSocialNetCore.Client.IAsynchronousClient asyncClient, Abp.ErmesSocialNetCore.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Abp.ErmesSocialNetCore.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Abp.ErmesSocialNetCore.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Abp.ErmesSocialNetCore.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Abp.ErmesSocialNetCore.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Abp.ErmesSocialNetCore.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets a paged list of media entities Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <returns>Pagination</returns>
        public Pagination ApiV1MediaGet(int? page = default(int?), int? limit = default(int?))
        {
            Abp.ErmesSocialNetCore.Client.ApiResponse<Pagination> localVarResponse = ApiV1MediaGetWithHttpInfo(page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a paged list of media entities Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <returns>ApiResponse of Pagination</returns>
        public Abp.ErmesSocialNetCore.Client.ApiResponse<Pagination> ApiV1MediaGetWithHttpInfo(int? page = default(int?), int? limit = default(int?))
        {
            Abp.ErmesSocialNetCore.Client.RequestOptions localVarRequestOptions = new Abp.ErmesSocialNetCore.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (api_secret) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Secret")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Secret", this.Configuration.GetApiKeyWithPrefix("X-API-Secret"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Pagination>("/api/v1/media", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1MediaGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a paged list of media entities Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Pagination</returns>
        public async System.Threading.Tasks.Task<Pagination> ApiV1MediaGetAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Abp.ErmesSocialNetCore.Client.ApiResponse<Pagination> localVarResponse = await ApiV1MediaGetWithHttpInfoAsync(page, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a paged list of media entities Retrieves a paged list of media, or a single media if the ID is provided in path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">which page to retrieve (optional)</param>
        /// <param name="limit">how many instances per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Pagination)</returns>
        public async System.Threading.Tasks.Task<Abp.ErmesSocialNetCore.Client.ApiResponse<Pagination>> ApiV1MediaGetWithHttpInfoAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Abp.ErmesSocialNetCore.Client.RequestOptions localVarRequestOptions = new Abp.ErmesSocialNetCore.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (api_secret) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Secret")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Secret", this.Configuration.GetApiKeyWithPrefix("X-API-Secret"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Pagination>("/api/v1/media", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1MediaGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a single media entity Retrieves a single media entity from the ID provided in the path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <returns>Media</returns>
        public Media ApiV1MediaMediaIdGet(long mediaId)
        {
            Abp.ErmesSocialNetCore.Client.ApiResponse<Media> localVarResponse = ApiV1MediaMediaIdGetWithHttpInfo(mediaId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single media entity Retrieves a single media entity from the ID provided in the path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <returns>ApiResponse of Media</returns>
        public Abp.ErmesSocialNetCore.Client.ApiResponse<Media> ApiV1MediaMediaIdGetWithHttpInfo(long mediaId)
        {
            Abp.ErmesSocialNetCore.Client.RequestOptions localVarRequestOptions = new Abp.ErmesSocialNetCore.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("media_id", Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToString(mediaId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (api_secret) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Secret")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Secret", this.Configuration.GetApiKeyWithPrefix("X-API-Secret"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Media>("/api/v1/media/{media_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1MediaMediaIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a single media entity Retrieves a single media entity from the ID provided in the path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Media</returns>
        public async System.Threading.Tasks.Task<Media> ApiV1MediaMediaIdGetAsync(long mediaId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Abp.ErmesSocialNetCore.Client.ApiResponse<Media> localVarResponse = await ApiV1MediaMediaIdGetWithHttpInfoAsync(mediaId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single media entity Retrieves a single media entity from the ID provided in the path.
        /// </summary>
        /// <exception cref="Abp.ErmesSocialNetCore.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">ID of the media</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Media)</returns>
        public async System.Threading.Tasks.Task<Abp.ErmesSocialNetCore.Client.ApiResponse<Media>> ApiV1MediaMediaIdGetWithHttpInfoAsync(long mediaId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Abp.ErmesSocialNetCore.Client.RequestOptions localVarRequestOptions = new Abp.ErmesSocialNetCore.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Abp.ErmesSocialNetCore.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("media_id", Abp.ErmesSocialNetCore.Client.ClientUtils.ParameterToString(mediaId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (api_secret) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Secret")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Secret", this.Configuration.GetApiKeyWithPrefix("X-API-Secret"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Media>("/api/v1/media/{media_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1MediaMediaIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
